import Link from 'next/link'
import {AlertTriangle,Banknote,CalendarClock,CircleDollarSign,ReceiptText,TrendingUp} from 'lucide-react'
import {Badge} from '@/components/ui/badge'
import {Button} from '@/components/ui/button'
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from '@/components/ui/card'
import {formatEtb} from '@/services/projects/supabase-project-service'
import {financeDate,financeStatusLabel,getFinanceWorkspace} from '@/services/finance/supabase-finance-service'
import {FinanceNav} from './finance-nav'
export default async function FinancePage(){
 const d=await getFinanceWorkspace();const total=d.receivables.reduce((s,r)=>s+Number(r.total_price_etb),0);const paid=d.receivables.reduce((s,r)=>s+Number(r.paid_etb),0);const outstanding=d.receivables.reduce((s,r)=>s+Number(r.outstanding_etb),0);const awaiting=d.payments.filter(p=>p.status==='submitted');const overdue=d.schedules.filter(s=>s.status!=='paid'&&s.due_date&&new Date(s.due_date)<new Date())
 const metrics=[{label:'Contracted sales',value:formatEtb(total),detail:'VAT-inclusive contract value',icon:CircleDollarSign},{label:'Collections',value:formatEtb(paid),detail:`${total?Math.round(paid/total*100):0}% collected`,icon:TrendingUp},{label:'Outstanding',value:formatEtb(outstanding),detail:'Remaining customer receivables',icon:CalendarClock},{label:'Awaiting verification',value:String(awaiting.length),detail:'Payments requiring finance review',icon:Banknote}]
 return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-primary">Finance Module</p><h2 className="mt-1 font-serif text-3xl font-semibold">Finance command center</h2><p className="mt-2 text-sm text-muted-foreground">Collections, balances, receipts, commissions and approved disbursements.</p></div><Button asChild><Link href="/erp/finance/payments/new">Record payment</Link></Button></div><FinanceNav/>
 <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{metrics.map(m=><Card key={m.label}><CardHeader className="flex flex-row items-start justify-between"><div><CardDescription>{m.label}</CardDescription><CardTitle className="mt-2 text-2xl">{m.value}</CardTitle></div><span className="rounded-lg bg-primary/10 p-2 text-primary"><m.icon className="size-5"/></span></CardHeader><CardContent className="text-sm text-muted-foreground">{m.detail}</CardContent></Card>)}</section>
 <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Card><CardHeader><CardTitle>Customer receivables</CardTitle><CardDescription>Open a contract to generate its schedule or review collections.</CardDescription></CardHeader><CardContent className="space-y-3">{d.receivables.slice(0,8).map(r=><Link key={r.contract_id} href={`/erp/finance/contracts/${r.contract_id}`} className="grid gap-3 rounded-lg border p-3 hover:border-primary md:grid-cols-[1.3fr_1fr_1fr_auto] md:items-center"><div><p className="font-medium">{r.customer_name}</p><p className="text-xs text-muted-foreground">{r.contract_number} · Unit {r.unit_number}</p></div><div><p className="text-xs text-muted-foreground">Paid</p><p className="text-sm font-semibold">{formatEtb(r.paid_etb)}</p></div><div><p className="text-xs text-muted-foreground">Outstanding</p><p className="text-sm font-semibold">{formatEtb(r.outstanding_etb)}</p></div><Badge variant="outline">{financeDate(r.next_due_date)}</Badge></Link>)}</CardContent></Card>
 <Card><CardHeader><CardTitle className="flex items-center gap-2"><AlertTriangle className="size-5"/>Attention needed</CardTitle></CardHeader><CardContent className="space-y-3"><div className="rounded-lg border p-3"><p className="text-sm font-medium">{awaiting.length} payments awaiting verification</p><Button asChild variant="link" className="px-0"><Link href="/erp/finance/payments">Review payments</Link></Button></div><div className="rounded-lg border p-3"><p className="text-sm font-medium">{overdue.length} overdue installments</p><Button asChild variant="link" className="px-0"><Link href="/erp/finance/receivables">Review receivables</Link></Button></div><div className="rounded-lg border p-3"><p className="text-sm font-medium">{d.commissions.filter(c=>c.status==='eligible').length} eligible commissions</p><Button asChild variant="link" className="px-0"><Link href="/erp/finance/commissions">Review commissions</Link></Button></div></CardContent></Card></div>
 </div>
}
