import Link from 'next/link'
import { AlertTriangle, CalendarCheck, CalendarClock, CalendarDays, CheckCircle2, CirclePlay, MapPin, Pencil, RotateCcw, Users, XCircle } from 'lucide-react'
import { eventWorkflowAction } from './actions'
import { EventCalendar } from '@/components/erp/events/event-calendar'
import { EventEditForm } from '@/components/erp/events/event-edit-form'
import { EventForm } from '@/components/erp/events/event-form'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { getEventsWorkspace } from '@/services/events/supabase-event-service'
import { eventCategories, eventDate, eventLabel, type ScheduledEvent } from '@/services/events/event-types'

const day=86400000
function workflow(event:ScheduledEvent,name:string,label:string,icon:typeof CheckCircle2,variant:'default'|'outline'|'destructive'='outline'){const Icon=icon;return <form action={eventWorkflowAction.bind(null,event.id)}><input type="hidden" name="action" value={name}/><Button size="sm" variant={variant}><Icon className="size-3.5"/>{label}</Button></form>}

type Filters={status?:string;category?:string;view?:string;date?:string}
export default async function EventsPage({searchParams}:{searchParams:Promise<Filters>}){
  const [data,filters]=await Promise.all([getEventsWorkspace(),searchParams])
  const now=new Date(),todayStart=new Date(now);todayStart.setHours(0,0,0,0)
  const todayEnd=new Date(todayStart.getTime()+day),weekEnd=new Date(now.getTime()+7*day)
  const projectMap=new Map(data.projects.map(project=>[project.id,project]))
  const peopleMap=new Map(data.people.map(person=>[person.id,person]))
  const visible=data.events.filter(event=>(!filters.status||event.status===filters.status)&&(!filters.category||event.category===filters.category))
  const today=data.events.filter(event=>new Date(event.starts_at)>=todayStart&&new Date(event.starts_at)<todayEnd&&event.status!=='cancelled')
  const upcoming=data.events.filter(event=>new Date(event.starts_at)>=now&&new Date(event.starts_at)<=weekEnd&&event.status==='scheduled')
  const overdue=data.events.filter(event=>new Date(event.starts_at)<now&&['scheduled','in_progress'].includes(event.status))
  const completed=data.events.filter(event=>event.status==='completed')
  const view=filters.view==='month'||filters.view==='week'?filters.view:'timeline'
  const metrics=[{label:'Today',value:today.length,detail:'Events scheduled today',icon:CalendarDays},{label:'Next 7 days',value:upcoming.length,detail:'Upcoming commitments',icon:CalendarClock},{label:'Overdue',value:overdue.length,detail:'Needs action or rescheduling',icon:AlertTriangle},{label:'Completed',value:completed.length,detail:'Closed events',icon:CalendarCheck}]
  return <div className="space-y-6">
    <div className="rounded-2xl bg-[linear-gradient(135deg,#082945,#0f4268)] px-6 py-7 text-white shadow-xl"><p className="text-xs font-semibold uppercase tracking-[.22em] text-gold">Events module</p><h2 className="mt-2 font-serif text-3xl font-semibold">Plan. Coordinate. Deliver.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/70">Manage meetings, inspections, deadlines, attendees and automatic reminders from one operational calendar.</p></div>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{metrics.map(metric=><Card key={metric.label} className="border-primary/10 shadow-sm"><CardHeader className="flex flex-row items-start justify-between"><div><CardDescription>{metric.label}</CardDescription><CardTitle className="mt-2 text-3xl">{metric.value}</CardTitle></div><span className="rounded-xl bg-gold/15 p-2.5 text-primary"><metric.icon className="size-5"/></span></CardHeader><CardContent className="text-sm text-muted-foreground">{metric.detail}</CardContent></Card>)}</section>
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-xl border bg-card p-1 shadow-sm">{(['timeline','month','week'] as const).map(item=><Button asChild key={item} size="sm" variant={view===item?'default':'ghost'}><Link href={`/erp/events?view=${item}`}>{eventLabel(item)}</Link></Button>)}</div><form className="flex flex-wrap gap-2"><input type="hidden" name="view" value={view}/><select name="status" defaultValue={filters.status??''} className="h-9 rounded-lg border border-input bg-background px-3 text-sm"><option value="">All statuses</option>{['scheduled','in_progress','completed','cancelled'].map(status=><option key={status} value={status}>{eventLabel(status)}</option>)}</select><select name="category" defaultValue={filters.category??''} className="h-9 rounded-lg border border-input bg-background px-3 text-sm"><option value="">All categories</option>{eventCategories.map(category=><option key={category} value={category}>{eventLabel(category)}</option>)}</select><Button type="submit" size="sm" variant="outline">Apply</Button></form></div>
    {view==='month'||view==='week'?<EventCalendar events={visible} view={view} selectedDate={filters.date}/>:null}
    <div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]">
      <Card className="h-fit border-primary/10 shadow-sm"><CardHeader><CardTitle>Schedule an event</CardTitle><CardDescription>Create a project commitment with attendees and an automatic reminder.</CardDescription></CardHeader><CardContent><EventForm projects={data.projects} people={data.people}/></CardContent></Card>
      <Card className="border-primary/10 shadow-sm"><CardHeader><CardTitle>{view==='timeline'?'Event timeline':'Event details'}</CardTitle><CardDescription>{visible.length} events match the current view.</CardDescription></CardHeader><CardContent className="space-y-3">{visible.map(event=>{const project=projectMap.get(event.project_id),owner=event.owner_id?peopleMap.get(event.owner_id):null;return <article key={event.id} className="rounded-xl border bg-card p-4 transition hover:border-gold/40"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-primary">{event.title}</p><Badge variant="outline">{eventLabel(event.category)}</Badge><Badge variant={event.priority==='urgent'?'destructive':'secondary'}>{eventLabel(event.priority)}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{event.event_number} Â· {project?.code} Â· {eventDate(event.starts_at,!event.all_day)}</p></div><Badge>{eventLabel(event.status)}</Badge></div>{event.description?<p className="mt-3 text-sm text-muted-foreground">{event.description}</p>:null}<div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted-foreground">{event.location?<span className="flex items-center gap-1"><MapPin className="size-3"/>{event.location}</span>:null}<span>Owner: {owner?.full_name??'Event creator'}</span><span className="flex items-center gap-1"><Users className="size-3"/>{event.attendee_ids.length} attendee{event.attendee_ids.length===1?'':'s'}</span>{event.reminder_minutes[0]?<span>Reminder: {event.reminder_minutes[0]>=1440?`${event.reminder_minutes[0]/1440} day(s)`:`${event.reminder_minutes[0]} min`} before</span>:null}</div><div className="mt-4 flex flex-wrap gap-2">{event.status==='scheduled'?workflow(event,'start','Start',CirclePlay):null}{['scheduled','in_progress'].includes(event.status)?workflow(event,'complete','Complete',CheckCircle2,'default'):null}{!['completed','cancelled'].includes(event.status)?workflow(event,'cancel','Cancel',XCircle,'destructive'):null}{['completed','cancelled'].includes(event.status)?workflow(event,'reopen','Reopen',RotateCcw):null}<details className="w-full"><summary className="mt-2 inline-flex cursor-pointer list-none items-center gap-2 rounded-lg border px-3 py-2 text-sm font-medium hover:bg-muted"><Pencil className="size-3.5"/>Edit or reschedule</summary><EventEditForm event={event} projects={data.projects} people={data.people}/></details></div></article>})}{visible.length===0?<div className="py-14 text-center"><CalendarDays className="mx-auto size-9 text-muted-foreground"/><p className="mt-3 text-sm text-muted-foreground">No scheduled events match this view.</p></div>:null}</CardContent></Card>
    </div>
  </div>
}
