import{Badge}from'@/components/ui/badge'
import{Button}from'@/components/ui/button'
import{Card,CardContent,CardDescription,CardHeader,CardTitle}from'@/components/ui/card'
import{contractAction}from'../actions'
import{ContractForm}from'../contractor-forms'
import{ContractorNav}from'../contractor-nav'
import{contractorDate,contractorEtb,contractorLabel,getContractorWorkspace}from'@/services/contractors/supabase-contractor-service'
export default async function ContractsPage(){const d=await getContractorWorkspace();const contractors=new Map(d.contractors.map(c=>[c.id,c]));const projects=new Map(d.projects.map(p=>[p.id,p]));const packages=new Map(d.workPackages.map(w=>[w.id,w]));return <div className="space-y-6"><div><p className="text-sm font-medium text-primary">Contractors</p><h2 className="mt-1 font-serif text-3xl font-semibold">Project contracts</h2><p className="mt-2 text-sm text-muted-foreground">Controlled appointments linked to Construction work packages.</p></div><ContractorNav/><Card><CardHeader><CardTitle>Create contractor contract</CardTitle><CardDescription>Only approved contractors can be appointed.</CardDescription></CardHeader><CardContent><ContractForm projects={d.projects} contractors={d.contractors} workPackages={d.workPackages}/></CardContent></Card><div className="space-y-4">{d.contracts.map(c=><Card key={c.id}><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle>{c.contract_number} · {c.title}</CardTitle><CardDescription>{contractors.get(c.contractor_id)?.legal_name} · {projects.get(c.project_id)?.name}{c.work_package_id?` · ${packages.get(c.work_package_id)?.code}`:''}</CardDescription></div><Badge>{contractorLabel(c.status)}</Badge></div></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 text-sm md:grid-cols-4"><div><p className="text-muted-foreground">Contract value</p><p className="font-semibold">{contractorEtb(c.contract_value_etb)}</p></div><div><p className="text-muted-foreground">Retention</p><p className="font-semibold">{c.retention_rate}%</p></div><div><p className="text-muted-foreground">Start</p><p className="font-semibold">{contractorDate(c.start_date)}</p></div><div><p className="text-muted-foreground">End</p><p className="font-semibold">{contractorDate(c.end_date)}</p></div></div><p className="text-sm text-muted-foreground">{c.scope_of_work}</p>{c.termination_reason?<p className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{c.termination_reason}</p>:null}<div className="flex flex-wrap gap-2">{c.status==='draft'?<Action id={c.id} action="approve" label="Approve contract"/>:null}{c.status==='approved'?<Action id={c.id} action="activate" label="Activate"/>:null}{c.status==='active'?<><Action id={c.id} action="complete" label="Complete"/><Action id={c.id} action="suspend" label="Suspend" variant="outline"/><Action id={c.id} action="terminate" label="Terminate" variant="destructive"/></>:null}{c.status==='suspended'?<><Action id={c.id} action="resume" label="Resume"/><Action id={c.id} action="terminate" label="Terminate" variant="destructive"/></>:null}</div></CardContent></Card>)}{d.contracts.length===0?<Card><CardContent className="py-14 text-center text-sm text-muted-foreground">No contractor contracts yet. Approve a contractor first.</CardContent></Card>:null}</div></div>}
function Action({id,action,label,variant}:{id:string;action:string;label:string;variant?:'outline'|'destructive'}){return <form action={contractAction.bind(null,id)}><input type="hidden" name="action" value={action}/><Button type="submit" variant={variant}>{label}</Button></form>}
