import Link from 'next/link'
import {ArrowRight,WalletCards} from 'lucide-react'
import {Badge} from '@/components/ui/badge'
import {Button} from '@/components/ui/button'
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from '@/components/ui/card'
import {formatEtb} from '@/services/projects/supabase-project-service'
import {financeDate,getFinanceWorkspace} from '@/services/finance/supabase-finance-service'
import {FinanceNav} from '../finance-nav'
export default async function ReceivablesPage(){const d=await getFinanceWorkspace();return <div className="space-y-6"><div><p className="text-sm font-medium text-primary">Finance</p><h2 className="mt-1 font-serif text-3xl font-semibold">Customer receivables</h2><p className="mt-2 text-sm text-muted-foreground">Every contract, installment, collection and outstanding balance.</p></div><FinanceNav/><div className="space-y-4">{d.receivables.map(r=>{const pct=Number(r.total_price_etb)?Math.round(Number(r.paid_etb)/Number(r.total_price_etb)*100):0;return <Card key={r.contract_id}><CardHeader><div className="flex flex-wrap justify-between gap-3"><div><CardTitle>{r.customer_name}</CardTitle><CardDescription>{r.project_name} · Unit {r.unit_number} · {r.contract_number}</CardDescription></div><Badge variant={Number(r.outstanding_etb)<=0?'default':'outline'}>{Number(r.outstanding_etb)<=0?'Fully paid':`${pct}% collected`}</Badge></div></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-4"><div><p className="text-xs text-muted-foreground">Contract</p><p className="font-semibold">{formatEtb(r.total_price_etb)}</p></div><div><p className="text-xs text-muted-foreground">Collected</p><p className="font-semibold">{formatEtb(r.paid_etb)}</p></div><div><p className="text-xs text-muted-foreground">Outstanding</p><p className="font-semibold">{formatEtb(r.outstanding_etb)}</p></div><div><p className="text-xs text-muted-foreground">Next due</p><p className="font-semibold">{financeDate(r.next_due_date)}</p></div></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary" style={{width:`${Math.min(100,pct)}%`}}/></div><Button asChild><Link href={`/erp/finance/contracts/${r.contract_id}`}>Open contract finance workspace<ArrowRight className="size-4"/></Link></Button></CardContent></Card>})}{d.receivables.length===0?<Card><CardContent className="py-14 text-center"><WalletCards className="mx-auto size-9 text-muted-foreground"/><p className="mt-3 text-sm text-muted-foreground">Sales CRM contracts will appear here.</p></CardContent></Card>:null}</div></div>}
