import type { Building, Floor, Project, Unit } from '@/types/erp'

const now = '2026-06-26T00:00:00.000Z'

export const projects: Project[] = [
  {
    id: 'project-alet-main',
    organizationId: 'org-alet',
    name: 'Alet Main Project',
    code: 'AMP',
    status: 'active',
    location: 'Addis Ababa',
    activeUnitCount: 64,
    soldUnitCount: 18,
    reservedUnitCount: 9,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'project-summit-residence',
    organizationId: 'org-alet',
    name: 'Summit Residence',
    code: 'SMR',
    status: 'planning',
    location: 'Summit, Addis Ababa',
    activeUnitCount: 42,
    soldUnitCount: 0,
    reservedUnitCount: 0,
    createdAt: now,
    updatedAt: now,
  },
]

export const buildings: Building[] = [
  {
    id: 'building-tower-a',
    organizationId: 'org-alet',
    projectId: 'project-alet-main',
    name: 'Tower A',
    floorCount: 12,
    unitCount: 48,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'building-tower-b',
    organizationId: 'org-alet',
    projectId: 'project-alet-main',
    name: 'Tower B',
    floorCount: 10,
    unitCount: 36,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'building-summit-a',
    organizationId: 'org-alet',
    projectId: 'project-summit-residence',
    name: 'Block A',
    floorCount: 8,
    unitCount: 42,
    createdAt: now,
    updatedAt: now,
  },
]

export const floors: Floor[] = [
  {
    id: 'floor-tower-a-05',
    organizationId: 'org-alet',
    projectId: 'project-alet-main',
    buildingId: 'building-tower-a',
    floorNumber: 5,
    unitCount: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'floor-tower-a-06',
    organizationId: 'org-alet',
    projectId: 'project-alet-main',
    buildingId: 'building-tower-a',
    floorNumber: 6,
    unitCount: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'floor-tower-b-03',
    organizationId: 'org-alet',
    projectId: 'project-alet-main',
    buildingId: 'building-tower-b',
    floorNumber: 3,
    unitCount: 4,
    createdAt: now,
    updatedAt: now,
  },
]

export const units: Unit[] = [
  {
    id: 'unit-a-0501',
    organizationId: 'org-alet',
    projectId: 'project-alet-main',
    buildingId: 'building-tower-a',
    floorId: 'floor-tower-a-05',
    unitNumber: 'A-0501',
    type: '2br',
    sizeSqm: 98,
    basePrice: 12800000,
    status: 'available',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'unit-a-0502',
    organizationId: 'org-alet',
    projectId: 'project-alet-main',
    buildingId: 'building-tower-a',
    floorId: 'floor-tower-a-05',
    unitNumber: 'A-0502',
    type: '3br',
    sizeSqm: 126,
    basePrice: 16500000,
    status: 'under_payment',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'unit-a-0601',
    organizationId: 'org-alet',
    projectId: 'project-alet-main',
    buildingId: 'building-tower-a',
    floorId: 'floor-tower-a-06',
    unitNumber: 'A-0601',
    type: '1br',
    sizeSqm: 72,
    basePrice: 9400000,
    status: 'reserved',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'unit-b-0301',
    organizationId: 'org-alet',
    projectId: 'project-alet-main',
    buildingId: 'building-tower-b',
    floorId: 'floor-tower-b-03',
    unitNumber: 'B-0301',
    type: 'studio',
    sizeSqm: 48,
    basePrice: 6200000,
    status: 'draft',
    createdAt: now,
    updatedAt: now,
  },
]
