import Link from 'next/link'
import{AlertTriangle,Archive,Boxes,ClipboardCheck,ScrollText}from 'lucide-react'
import{Badge}from '@/components/ui/badge'
import{Button}from '@/components/ui/button'
import{Card,CardContent,CardDescription,CardHeader,CardTitle}from '@/components/ui/card'
import{getInventoryWorkspace,inventoryDate,inventoryEtb,inventoryLabel}from '@/services/inventory/supabase-inventory-service'
import{InventoryNav}from './inventory-nav'

export default async function InventoryPage(){
 const d=await getInventoryWorkspace();const items=new Map(d.items.map(i=>[i.id,i]));const locations=new Map(d.locations.map(l=>[l.id,l]))
 const totalValue=d.stock.reduce((sum,s)=>sum+Number(s.quantity_on_hand)*Number(s.average_unit_cost_etb),0)
 const lowStock=d.stock.filter(s=>Number(s.quantity_on_hand)-Number(s.reserved_quantity)<=Number(items.get(s.item_id)?.minimum_stock??0))
 const pending=d.issues.filter(i=>['draft','submitted','approved'].includes(i.status))
 const metrics=[{label:'Stock value',value:inventoryEtb(totalValue),detail:`${d.stock.length} item balances`,icon:Boxes},{label:'Low stock',value:lowStock.length,detail:'At or below reorder level',icon:AlertTriangle},{label:'Issue queue',value:pending.length,detail:'Draft, approval and issue stages',icon:ClipboardCheck},{label:'Posted receipts',value:d.receipts.length,detail:'Accepted Procurement deliveries',icon:Archive}]
 return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-primary">Inventory Module</p><h2 className="mt-1 font-serif text-3xl font-semibold">Materials control center</h2><p className="mt-2 text-sm text-muted-foreground">Project stock, construction issues and Procurement receipts in one accountable ledger.</p></div><Button asChild><Link href="/erp/inventory/issues">Request stock</Link></Button></div><InventoryNav/>
 <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{metrics.map(m=><Card key={m.label}><CardHeader className="flex flex-row items-start justify-between"><div><CardDescription>{m.label}</CardDescription><CardTitle className="mt-2 text-2xl">{m.value}</CardTitle></div><span className="rounded-lg bg-primary/10 p-2 text-primary"><m.icon className="size-5"/></span></CardHeader><CardContent className="text-sm text-muted-foreground">{m.detail}</CardContent></Card>)}</section>
 <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Card><CardHeader><CardTitle>Recent stock activity</CardTitle><CardDescription>Receipts, issues and controlled adjustments.</CardDescription></CardHeader><CardContent className="space-y-3">{d.movements.slice(0,8).map(m=><Link key={m.id} href="/erp/inventory/movements" className="grid gap-2 rounded-lg border p-3 hover:border-primary md:grid-cols-[1fr_auto_auto] md:items-center"><div><p className="font-medium">{m.movement_number} · {items.get(m.item_id)?.name}</p><p className="text-xs text-muted-foreground">{locations.get(m.location_id)?.name} · {inventoryDate(m.created_at)}</p></div><p className="text-sm font-semibold">{m.quantity} {items.get(m.item_id)?.unit}</p><Badge variant="outline">{inventoryLabel(m.movement_type)}</Badge></Link>)}{d.movements.length===0?<div className="py-12 text-center"><ScrollText className="mx-auto size-8 text-muted-foreground"/><p className="mt-3 text-sm text-muted-foreground">No stock activity yet. Add a location and catalog item, or accept a Procurement delivery.</p></div>:null}</CardContent></Card>
 <Card><CardHeader><CardTitle>Attention needed</CardTitle></CardHeader><CardContent className="space-y-3"><Link href="/erp/inventory/stock" className="flex items-center justify-between rounded-lg border p-3 hover:border-primary"><span className="text-sm font-medium">Low-stock balances</span><Badge>{lowStock.length}</Badge></Link><Link href="/erp/inventory/issues" className="flex items-center justify-between rounded-lg border p-3 hover:border-primary"><span className="text-sm font-medium">Issue requests</span><Badge>{pending.length}</Badge></Link><Link href="/erp/inventory/receipts" className="flex items-center justify-between rounded-lg border p-3 hover:border-primary"><span className="text-sm font-medium">Procurement receipts</span><Badge>{d.receipts.length}</Badge></Link></CardContent></Card></div></div>
}
