import Link from 'next/link'
import {notFound} from 'next/navigation'
import {ArrowLeft,CheckCircle2,Layers3} from 'lucide-react'
import {Badge} from '@/components/ui/badge'
import {Button} from '@/components/ui/button'
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from '@/components/ui/card'
import {constructionDate,constructionFloorLabel,constructionLabel,getConstructionProject} from '@/services/construction/supabase-construction-service'
import {completeFloorAction} from '../../actions'
import {ConstructionNav} from '../../construction-nav'
type Props={params:Promise<{projectId:string}>}
export default async function ConstructionProjectPage({params}:Props){const{projectId}=await params;const d=await getConstructionProject(projectId);if(!d)notFound();const p=d.project;return <div className="space-y-6"><Button asChild variant="ghost"><Link href="/erp/construction/projects"><ArrowLeft className="size-4"/>Back to projects</Link></Button><div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm font-medium text-primary">Construction workspace</p><h2 className="mt-1 font-serif text-3xl font-semibold">{p.name}</h2><p className="mt-2 text-sm text-muted-foreground">{constructionLabel(p.phase)} · Expected {constructionDate(p.expected_completion_date)}</p></div><Badge>{p.floors_completed} of {p.total_floors} floors completed</Badge></div><ConstructionNav/><Card><CardHeader><CardTitle className="flex items-center gap-2"><Layers3 className="size-5"/>Floor progress</CardTitle><CardDescription>A floor can be completed only after its linked work packages are approved or completed.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{d.floors.map(f=>{const work=d.packages.filter(w=>w.floor_id===f.id);const ready=work.length===0||work.every(w=>['approved','completed','cancelled'].includes(w.status));return <div key={f.id} className={`rounded-lg border p-3 ${f.is_completed?'bg-emerald-50':''}`}><div className="flex justify-between"><div><p className="font-semibold">{constructionFloorLabel(f)}</p><p className="text-xs text-muted-foreground">{work.length} work packages</p></div>{f.is_completed?<CheckCircle2 className="size-5 text-emerald-600"/>:<Badge variant="outline">{ready?'Ready':'In progress'}</Badge>}</div>{!f.is_completed&&ready?<form action={completeFloorAction.bind(null,f.id)} className="mt-3"><input type="hidden" name="project_id" value={p.id}/><Button type="submit" size="sm">Complete floor</Button></form>:null}</div>})}</CardContent></Card><div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader><CardTitle>Active work</CardTitle></CardHeader><CardContent className="space-y-2">{d.packages.filter(w=>!['completed','cancelled'].includes(w.status)).map(w=><Link key={w.id} href="/erp/construction/work-packages" className="flex justify-between rounded-lg border p-3 hover:border-primary"><div><p className="font-medium">{w.code} · {w.title}</p><p className="text-xs text-muted-foreground">{w.contractor_name??'No contractor'}</p></div><Badge>{w.progress_percent}%</Badge></Link>)}</CardContent></Card><Card><CardHeader><CardTitle>Recent site activity</CardTitle></CardHeader><CardContent className="space-y-2">{d.reports.slice(0,5).map(r=><div key={r.id} className="rounded-lg border p-3"><div className="flex justify-between"><p className="font-medium">{constructionDate(r.report_date)}</p><Badge>{constructionLabel(r.status)}</Badge></div><p className="mt-2 line-clamp-2 text-sm text-muted-foreground">{r.work_performed}</p></div>)}</CardContent></Card></div></div>}
