'use server'
import {cookies} from 'next/headers'
import {revalidatePath} from 'next/cache'
import {getSupabaseServerConfig} from '@/lib/supabase/server'
const cookieName='alet-erp-session'
export type ConstructionActionState={error?:string;success?:string}
function value(fd:FormData,k:string){return String(fd.get(k)??'').trim()}
async function rpc(name:string,payload:Record<string,unknown>){const{url,anonKey}=getSupabaseServerConfig();const token=(await cookies()).get(cookieName)?.value;if(!token)throw new Error('Your ERP session expired. Sign in again.');const r=await fetch(`${url}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:anonKey,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({payload}),cache:'no-store'});const out=await r.json().catch(()=>({})) as{message?:string};if(!r.ok)throw new Error(out.message??'Construction could not save this change.');return out}
function refresh(projectId?:string){revalidatePath('/erp/construction');revalidatePath('/erp/construction/projects');revalidatePath('/erp/construction/work-packages');revalidatePath('/erp/construction/daily-reports');revalidatePath('/erp/construction/inspections');revalidatePath('/erp/construction/issues');revalidatePath('/erp/construction/milestones');if(projectId)revalidatePath(`/erp/construction/projects/${projectId}`)}

export async function createWorkPackageAction(_s:ConstructionActionState,fd:FormData):Promise<ConstructionActionState>{try{const p=value(fd,'project_id');await rpc('create_construction_work_package',{project_id:p,floor_id:value(fd,'floor_id'),code:value(fd,'code'),title:value(fd,'title'),category:value(fd,'category'),description:value(fd,'description'),priority:value(fd,'priority'),progress_percent:value(fd,'progress_percent'),planned_start:value(fd,'planned_start'),planned_finish:value(fd,'planned_finish'),assigned_to:value(fd,'assigned_to'),contractor_name:value(fd,'contractor_name'),dependencies:value(fd,'dependencies'),inspection_required:fd.get('inspection_required')==='on',public_summary:value(fd,'public_summary')});refresh(p);return{success:'Work package created.'}}catch(e){return{error:e instanceof Error?e.message:'Unable to create work package.'}}}
export async function updateWorkPackageAction(id:string,projectId:string,_s:ConstructionActionState,fd:FormData):Promise<ConstructionActionState>{try{await rpc('update_construction_work_package',{work_package_id:id,title:value(fd,'title'),description:value(fd,'description'),priority:value(fd,'priority'),status:value(fd,'status'),progress_percent:value(fd,'progress_percent'),planned_start:value(fd,'planned_start'),planned_finish:value(fd,'planned_finish'),assigned_to:value(fd,'assigned_to'),contractor_name:value(fd,'contractor_name'),dependencies:value(fd,'dependencies'),public_summary:value(fd,'public_summary')});refresh(projectId);return{success:'Work package updated.'}}catch(e){return{error:e instanceof Error?e.message:'Unable to update work package.'}}}
export async function createDailyReportAction(_s:ConstructionActionState,fd:FormData):Promise<ConstructionActionState>{try{const p=value(fd,'project_id');await rpc('create_construction_daily_report',{project_id:p,report_date:value(fd,'report_date'),weather:value(fd,'weather'),workforce_count:value(fd,'workforce_count'),work_performed:value(fd,'work_performed'),equipment_used:value(fd,'equipment_used'),materials_used:value(fd,'materials_used'),delays:value(fd,'delays'),safety_incidents:value(fd,'safety_incidents'),site_instructions:value(fd,'site_instructions'),next_day_plan:value(fd,'next_day_plan')});refresh(p);return{success:'Daily report saved as draft.'}}catch(e){return{error:e instanceof Error?e.message:'Unable to save daily report.'}}}
export async function reportAction(id:string,fd:FormData){await rpc('construction_report_action',{report_id:id,action:value(fd,'action'),comments:value(fd,'comments')});refresh()}
export async function createInspectionAction(_s:ConstructionActionState,fd:FormData):Promise<ConstructionActionState>{try{await rpc('create_construction_inspection',{work_package_id:value(fd,'work_package_id'),inspection_type:value(fd,'inspection_type'),inspector_id:value(fd,'inspector_id'),scheduled_at:value(fd,'scheduled_at'),comments:value(fd,'comments'),checklist:[]});refresh();return{success:'Inspection requested.'}}catch(e){return{error:e instanceof Error?e.message:'Unable to request inspection.'}}}
export async function inspectionAction(id:string,fd:FormData){await rpc('construction_inspection_action',{inspection_id:id,action:value(fd,'action'),comments:value(fd,'comments'),corrective_actions:value(fd,'corrective_actions'),scheduled_at:value(fd,'scheduled_at')});refresh()}
export async function createIssueAction(_s:ConstructionActionState,fd:FormData):Promise<ConstructionActionState>{try{const p=value(fd,'project_id');await rpc('create_construction_issue',{project_id:p,work_package_id:value(fd,'work_package_id'),floor_id:value(fd,'floor_id'),category:value(fd,'category'),priority:value(fd,'priority'),title:value(fd,'title'),description:value(fd,'description'),owner_id:value(fd,'owner_id'),due_date:value(fd,'due_date')});refresh(p);return{success:'Site issue recorded.'}}catch(e){return{error:e instanceof Error?e.message:'Unable to record issue.'}}}
export async function issueAction(id:string,fd:FormData){await rpc('construction_issue_action',{issue_id:id,action:value(fd,'action'),resolution:value(fd,'resolution')});refresh()}
export async function createMilestoneAction(_s:ConstructionActionState,fd:FormData):Promise<ConstructionActionState>{try{const p=value(fd,'project_id');await rpc('create_construction_milestone',{project_id:p,code:value(fd,'code'),title:value(fd,'title'),description:value(fd,'description'),phase:value(fd,'phase'),target_floor_number:value(fd,'target_floor_number'),planned_date:value(fd,'planned_date'),progress_percent:value(fd,'progress_percent'),finance_trigger:fd.get('finance_trigger')==='on',public_on_approval:fd.get('public_on_approval')==='on',public_summary:value(fd,'public_summary')});refresh(p);return{success:'Construction milestone created.'}}catch(e){return{error:e instanceof Error?e.message:'Unable to create milestone.'}}}
export async function milestoneAction(id:string,fd:FormData){await rpc('construction_milestone_action',{milestone_id:id,action:value(fd,'action'),reason:value(fd,'reason')});refresh()}
export async function completeFloorAction(id:string,fd:FormData){await rpc('complete_construction_floor',{floor_id:id});refresh(value(fd,'project_id'))}
