
create or replace function public.create_project_from_wizard(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  target_org uuid;
  target_user uuid := auth.uid();
  new_project public.projects;
  new_unit_type public.unit_types;
  typical_template public.floor_templates;
  special_template public.floor_templates;
  floor_number integer;
  position_number integer;
  total_floor_count integer := greatest(coalesce((payload->>'total_floors')::integer, 1), 1);
  units_per_floor integer := greatest(coalesce((payload->>'units_per_floor')::integer, 1), 1);
  special_units_per_floor integer := greatest(coalesce((payload->>'special_units_per_floor')::integer, 1), 1);
  is_special boolean;
  should_publish boolean := coalesce((payload->>'publish')::boolean, false);
  media_url text := nullif(trim(payload->>'media_url'), '');
  generated integer;
begin
  if target_user is null then
    raise exception 'Authentication required';
  end if;

  target_org := private.current_organization_id();

  if target_org is null
     or not private.has_project_role(array['admin','project_manager'], null) then
    raise exception 'Project creation requires administrator or project manager permission';
  end if;

  if nullif(trim(payload->>'name'), '') is null
     or nullif(trim(payload->>'code'), '') is null then
    raise exception 'Project name and code are required';
  end if;

  if should_publish and media_url is null then
    raise exception 'An approved public media URL is required before publication';
  end if;

  insert into public.projects (
    organization_id, name, code, slug, status, phase,
    marketing_title, short_description, description,
    address, city, subcity, latitude, longitude, google_maps_url,
    amenities, payment_plan_summary, offers, expected_completion_date,
    parking_price, vat_rate, total_floors, floors_completed, responsible_user_id
  ) values (
    target_org,
    trim(payload->>'name'),
    upper(trim(payload->>'code')),
    coalesce(
      nullif(trim(payload->>'slug'), ''),
      lower(trim(both '-' from regexp_replace(payload->>'name', '[^a-zA-Z0-9]+', '-', 'g')))
    ),
    case when payload->>'phase' = 'planning_design' then 'planning'::public.project_status else 'active'::public.project_status end,
    coalesce(nullif(payload->>'phase','')::public.project_phase, 'planning_design'),
    nullif(trim(payload->>'marketing_title'), ''),
    nullif(trim(payload->>'short_description'), ''),
    nullif(trim(payload->>'description'), ''),
    nullif(trim(payload->>'address'), ''),
    coalesce(nullif(trim(payload->>'city'), ''), 'Addis Ababa'),
    nullif(trim(payload->>'subcity'), ''),
    nullif(payload->>'latitude','')::numeric,
    nullif(payload->>'longitude','')::numeric,
    nullif(trim(payload->>'google_maps_url'), ''),
    coalesce(
      array(select trim(value) from jsonb_array_elements_text(coalesce(payload->'amenities','[]'::jsonb)) value where trim(value) <> ''),
      '{}'
    ),
    nullif(trim(payload->>'payment_plan_summary'), ''),
    nullif(trim(payload->>'offers'), ''),
    nullif(payload->>'expected_completion_date','')::date,
    greatest(coalesce((payload->>'parking_price')::numeric, 0), 0),
    greatest(coalesce((payload->>'vat_rate')::numeric, 15), 0),
    total_floor_count,
    least(greatest(coalesce((payload->>'floors_completed')::integer, 0), 0), total_floor_count),
    target_user
  )
  returning * into new_project;

  insert into public.unit_types (
    organization_id, project_id, code, name, category, bedrooms, bathrooms, description
  ) values (
    target_org,
    new_project.id,
    lower(trim(payload->>'unit_type_code')),
    trim(payload->>'unit_type_name'),
    coalesce(nullif(payload->>'unit_category','')::public.unit_category, 'residential'),
    nullif(payload->>'bedrooms','')::integer,
    nullif(payload->>'bathrooms','')::numeric,
    nullif(trim(payload->>'unit_type_description'), '')
  )
  returning * into new_unit_type;

  insert into public.floor_templates (
    organization_id, project_id, name, description, created_by
  ) values (
    target_org, new_project.id, 'Typical Floor', 'Generated by the new project wizard', target_user
  )
  returning * into typical_template;

  for position_number in 1..units_per_floor loop
    insert into public.floor_template_units (
      organization_id, project_id, template_id, position, unit_type_id,
      unit_number_pattern, size_sqm, bedrooms, bathrooms, balconies
    ) values (
      target_org, new_project.id, typical_template.id, position_number, new_unit_type.id,
      '{floor}-' || lpad(position_number::text, 2, '0'),
      greatest((payload->>'unit_size_sqm')::numeric, 1),
      nullif(payload->>'bedrooms','')::integer,
      nullif(payload->>'bathrooms','')::numeric,
      greatest(coalesce((payload->>'balconies')::integer, 0), 0)
    );
  end loop;

  if jsonb_array_length(coalesce(payload->'special_floors','[]'::jsonb)) > 0 then
    insert into public.floor_templates (
      organization_id, project_id, name, description, created_by
    ) values (
      target_org, new_project.id, 'Special Floor Override', 'Independent special-floor configuration', target_user
    )
    returning * into special_template;

    for position_number in 1..special_units_per_floor loop
      insert into public.floor_template_units (
        organization_id, project_id, template_id, position, unit_type_id,
        unit_number_pattern, size_sqm, bedrooms, bathrooms, balconies
      ) values (
        target_org, new_project.id, special_template.id, position_number, new_unit_type.id,
        '{floor}-S' || lpad(position_number::text, 2, '0'),
        greatest(coalesce((payload->>'special_unit_size_sqm')::numeric, (payload->>'unit_size_sqm')::numeric), 1),
        nullif(payload->>'bedrooms','')::integer,
        nullif(payload->>'bathrooms','')::numeric,
        greatest(coalesce((payload->>'balconies')::integer, 0), 0)
      );
    end loop;
  end if;

  for floor_number in 1..total_floor_count loop
    select exists (
      select 1
      from jsonb_array_elements_text(coalesce(payload->'special_floors','[]'::jsonb)) value
      where value::integer = floor_number
    ) into is_special;

    insert into public.project_floors (
      organization_id, project_id, floor_number, name, floor_kind, template_id,
      is_completed, completed_at, sequence
    ) values (
      target_org,
      new_project.id,
      floor_number,
      'Floor ' || floor_number,
      case when is_special then 'special' else 'typical' end,
      case when is_special then special_template.id else typical_template.id end,
      floor_number <= new_project.floors_completed,
      case when floor_number <= new_project.floors_completed then now() else null end,
      floor_number
    );
  end loop;

  insert into public.project_prices (
    organization_id, project_id, scope, unit_type_id, amount, currency,
    vat_rate, parking_price, change_reason, created_by
  ) values (
    target_org, new_project.id, 'unit_type', new_unit_type.id,
    greatest((payload->>'starting_price')::numeric, 0), 'ETB',
    new_project.vat_rate, new_project.parking_price, 'Initial wizard price', target_user
  );

  if media_url is not null then
    insert into public.project_media (
      organization_id, project_id, media_type, title, alt_text, public_url,
      is_hero, is_public, is_approved, uploaded_by
    ) values (
      target_org, new_project.id, 'image',
      coalesce(nullif(trim(payload->>'media_title'), ''), new_project.name),
      coalesce(nullif(trim(payload->>'media_alt_text'), ''), new_project.name),
      media_url, true, true, should_publish, target_user
    );
  end if;

  insert into public.project_milestones (
    organization_id, project_id, phase, title, description, progress_percent,
    floors_completed, total_floors, target_date, is_public, created_by
  ) values (
    target_org, new_project.id, new_project.phase,
    format('Current phase: %s', replace(initcap(new_project.phase::text), '_', ' ')),
    nullif(trim(payload->>'progress_description'), ''),
    least(greatest(coalesce((payload->>'progress_percent')::numeric, 0), 0), 100),
    new_project.floors_completed, new_project.total_floors,
    new_project.expected_completion_date, true, target_user
  );

  insert into public.project_publications (
    organization_id, project_id, status, submitted_by, submitted_at,
    approved_by, approved_at, published_at
  ) values (
    target_org,
    new_project.id,
    case when should_publish then 'published'::public.project_publication_status else 'draft'::public.project_publication_status end,
    case when should_publish then target_user else null end,
    case when should_publish then now() else null end,
    case when should_publish then target_user else null end,
    case when should_publish then now() else null end,
    case when should_publish then now() else null end
  );

  generated := public.generate_project_units(new_project.id);
  perform private.refresh_public_project(new_project.id);

  return jsonb_build_object(
    'project_id', new_project.id,
    'slug', new_project.slug,
    'generated_units', generated,
    'published', should_publish
  );
end
$$;

revoke all on function public.create_project_from_wizard(jsonb) from public, anon;
grant execute on function public.create_project_from_wizard(jsonb) to authenticated;
