import {Badge} from '@/components/ui/badge'
import {Button} from '@/components/ui/button'
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from '@/components/ui/card'
import {formatEtb} from '@/services/projects/supabase-project-service'
import {financeDate,financeStatusLabel,getFinanceWorkspace} from '@/services/finance/supabase-finance-service'
import {disbursementAction} from '../actions'
import {FinanceNav} from '../finance-nav'
import {DisbursementForm} from '../finance-forms'
export default async function DisbursementsPage(){const d=await getFinanceWorkspace();return <div className="space-y-6"><div><p className="text-sm font-medium text-primary">Finance</p><h2 className="mt-1 font-serif text-3xl font-semibold">Payments and disbursements</h2><p className="mt-2 text-sm text-muted-foreground">Approved payroll totals, reimbursements, commissions and other outgoing payments.</p></div><FinanceNav/><div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><Card><CardHeader><CardTitle>New disbursement</CardTitle><CardDescription>HR calculates payroll; Finance records and pays the approved total.</CardDescription></CardHeader><CardContent><DisbursementForm projects={d.projects}/></CardContent></Card><div className="space-y-3">{d.disbursements.map(x=><Card key={x.id}><CardContent className="space-y-4 pt-6"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold">{x.payee_name}</p><p className="text-xs text-muted-foreground">{x.disbursement_number} · {financeStatusLabel(x.disbursement_type)}</p></div><div className="text-right"><p className="font-semibold">{formatEtb(x.amount_etb)}</p><Badge>{financeStatusLabel(x.status)}</Badge></div></div><p className="text-sm text-muted-foreground">{x.description}</p><div className="flex flex-wrap gap-2">{x.status==='submitted'?<form action={disbursementAction.bind(null,x.id)}><input type="hidden" name="action" value="approve"/><Button type="submit">Approve</Button></form>:null}{x.status==='approved'?<form action={disbursementAction.bind(null,x.id)} className="flex flex-wrap gap-2"><input type="hidden" name="action" value="pay"/><input type="hidden" name="payment_method" value="bank_transfer"/><select name="account_id" className="h-8 rounded-lg border bg-background px-2 text-sm">{d.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><input name="bank_reference" placeholder="Bank reference" className="h-8 rounded-lg border px-2 text-sm"/><Button type="submit">Record payment</Button></form>:null}{x.status==='paid'?<form action={disbursementAction.bind(null,x.id)}><input type="hidden" name="action" value="reverse"/><input type="hidden" name="reason" value="Reversed from Finance workspace"/><Button type="submit" variant="destructive">Reverse</Button></form>:null}</div><p className="text-xs text-muted-foreground">Created {financeDate(x.created_at)}</p></CardContent></Card>)}{d.disbursements.length===0?<Card><CardContent className="py-14 text-center text-sm text-muted-foreground">No disbursements recorded.</CardContent></Card>:null}</div></div></div>}
