'use server'
import{cookies}from'next/headers'
import{revalidatePath}from'next/cache'
import{getSupabaseServerConfig}from'@/lib/supabase/server'
const cookieName='alet-erp-session'
export type ContractorActionState={error?:string;success?:string}
function value(fd:FormData,k:string){return String(fd.get(k)??'').trim()}
async function rpc(name:string,payload:Record<string,unknown>){const{url,anonKey}=getSupabaseServerConfig();const token=(await cookies()).get(cookieName)?.value;if(!token)throw new Error('Your ERP session expired. Sign in again.');const r=await fetch(`${url}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:anonKey,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({payload}),cache:'no-store'});const out=await r.json().catch(()=>({}))as{message?:string};if(!r.ok)throw new Error(out.message??'Contractor workflow could not save this change.');return out}
function refresh(){for(const p of['/erp/contractors','/erp/contractors/directory','/erp/contractors/contracts','/erp/contractors/claims','/erp/contractors/compliance','/erp/contractors/evaluations','/erp/construction/work-packages','/erp/finance/disbursements'])revalidatePath(p)}
export async function createContractorAction(_s:ContractorActionState,fd:FormData):Promise<ContractorActionState>{try{await rpc('create_contractor',{supplier_id:value(fd,'supplier_id'),contractor_code:value(fd,'contractor_code'),legal_name:value(fd,'legal_name'),trade_name:value(fd,'trade_name'),contractor_type:value(fd,'contractor_type'),specialization:value(fd,'specialization'),tax_id:value(fd,'tax_id'),license_number:value(fd,'license_number'),license_class:value(fd,'license_class'),contact_person:value(fd,'contact_person'),phone:value(fd,'phone'),email:value(fd,'email'),address:value(fd,'address'),bank_name:value(fd,'bank_name'),bank_account:value(fd,'bank_account')});refresh();return{success:'Contractor profile created as draft.'}}catch(e){return{error:e instanceof Error?e.message:'Unable to create contractor.'}}}
export async function contractorAction(id:string,fd:FormData){await rpc('contractor_action',{contractor_id:id,action:value(fd,'action'),score:value(fd,'score'),comments:value(fd,'comments')});refresh()}
export async function createContractAction(_s:ContractorActionState,fd:FormData):Promise<ContractorActionState>{try{await rpc('create_contractor_contract',{project_id:value(fd,'project_id'),contractor_id:value(fd,'contractor_id'),work_package_id:value(fd,'work_package_id'),contract_number:value(fd,'contract_number'),title:value(fd,'title'),scope_of_work:value(fd,'scope_of_work'),contract_type:value(fd,'contract_type'),contract_value_etb:value(fd,'contract_value_etb'),retention_rate:value(fd,'retention_rate'),advance_payment_etb:value(fd,'advance_payment_etb'),start_date:value(fd,'start_date'),end_date:value(fd,'end_date')});refresh();return{success:'Contract created as draft.'}}catch(e){return{error:e instanceof Error?e.message:'Unable to create contract.'}}}
export async function contractAction(id:string,fd:FormData){await rpc('contractor_contract_action',{contract_id:id,action:value(fd,'action'),comments:value(fd,'comments')});refresh()}
export async function complianceAction(_s:ContractorActionState,fd:FormData):Promise<ContractorActionState>{try{await rpc('record_contractor_compliance',{contractor_id:value(fd,'contractor_id'),project_id:value(fd,'project_id'),document_type:value(fd,'document_type'),reference_number:value(fd,'reference_number'),issued_date:value(fd,'issued_date'),expiry_date:value(fd,'expiry_date'),notes:value(fd,'notes')});refresh();return{success:'Compliance record verified.'}}catch(e){return{error:e instanceof Error?e.message:'Unable to record compliance.'}}}
export async function createClaimAction(_s:ContractorActionState,fd:FormData):Promise<ContractorActionState>{try{await rpc('create_contractor_claim',{contract_id:value(fd,'contract_id'),period_start:value(fd,'period_start'),period_end:value(fd,'period_end'),work_progress_percent:value(fd,'work_progress_percent'),gross_amount_etb:value(fd,'gross_amount_etb'),other_deductions_etb:value(fd,'other_deductions_etb'),description:value(fd,'description')});refresh();return{success:'Progress claim created as draft.'}}catch(e){return{error:e instanceof Error?e.message:'Unable to create claim.'}}}
export async function claimAction(id:string,fd:FormData){await rpc('contractor_claim_action',{claim_id:id,action:value(fd,'action'),comments:value(fd,'comments')});refresh()}
export async function evaluationAction(_s:ContractorActionState,fd:FormData):Promise<ContractorActionState>{try{await rpc('record_contractor_evaluation',{project_id:value(fd,'project_id'),contractor_id:value(fd,'contractor_id'),contract_id:value(fd,'contract_id'),evaluation_date:value(fd,'evaluation_date'),quality_score:value(fd,'quality_score'),schedule_score:value(fd,'schedule_score'),safety_score:value(fd,'safety_score'),commercial_score:value(fd,'commercial_score'),strengths:value(fd,'strengths'),concerns:value(fd,'concerns'),recommendation:value(fd,'recommendation')});refresh();return{success:'Contractor evaluation recorded.'}}catch(e){return{error:e instanceof Error?e.message:'Unable to record evaluation.'}}}
