import Link from 'next/link'
import {notFound} from 'next/navigation'
import {ArrowLeft} from 'lucide-react'
import {Badge} from '@/components/ui/badge'
import {Button} from '@/components/ui/button'
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from '@/components/ui/card'
import {formatEtb} from '@/services/projects/supabase-project-service'
import {financeDate,financeStatusLabel,getFinanceContract} from '@/services/finance/supabase-finance-service'
import {calculateCommissionAction,generateScheduleAction,paymentAction} from '../../actions'
import {InstallmentEditForm} from '../../finance-forms'
type Props={params:Promise<{contractId:string}>}
export default async function FinanceContractPage({params}:Props){const{contractId}=await params;const d=await getFinanceContract(contractId);if(!d)notFound();const c=d.contract;const customer=d.customers.find(x=>x.id===c.customer_id);const unit=d.units.find(x=>x.id===c.unit_id);const project=d.projects.find(x=>x.id===c.project_id);const receipts=new Map(d.receipts.map(r=>[r.payment_id,r]));return <div className="space-y-6"><Button asChild variant="ghost"><Link href="/erp/finance/receivables"><ArrowLeft className="size-4"/>Back to receivables</Link></Button>
 <div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm font-medium text-primary">{project?.name}</p><h2 className="mt-1 font-serif text-3xl font-semibold">{c.contract_number}</h2><p className="mt-2 text-sm text-muted-foreground">{customer?.full_name} · Unit {unit?.unit_number}</p></div><Badge>{financeStatusLabel(c.status)}</Badge></div>
 <section className="grid gap-4 md:grid-cols-4"><Card><CardHeader><CardDescription>Contract value</CardDescription><CardTitle>{formatEtb(c.total_price_etb)}</CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Collected</CardDescription><CardTitle>{formatEtb(d.receivable?.paid_etb??0)}</CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Outstanding</CardDescription><CardTitle>{formatEtb(d.receivable?.outstanding_etb??c.total_price_etb)}</CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Next due</CardDescription><CardTitle className="text-xl">{financeDate(d.receivable?.next_due_date??null)}</CardTitle></CardHeader></Card></section>
 <Card><CardHeader><div className="flex flex-wrap justify-between gap-3"><div><CardTitle>Payment schedule</CardTitle><CardDescription>Installments must always equal the VAT-inclusive contract total.</CardDescription></div>{d.schedules.length===0?<form action={generateScheduleAction.bind(null,c.id)}><Button type="submit">Generate from contract</Button></form>:null}</div></CardHeader><CardContent className="space-y-3">{d.schedules.map(s=><div key={s.id} className="space-y-2"><div className="flex flex-wrap justify-between gap-3 rounded-lg border p-3"><div><p className="font-medium">{s.installment_number}. {s.label}</p><p className="text-xs text-muted-foreground">{financeDate(s.due_date)} · {financeStatusLabel(s.trigger_type)}</p></div><div className="text-right"><p className="font-semibold">{formatEtb(s.amount_etb)}</p><Badge variant={s.status==='paid'?'default':'outline'}>{financeStatusLabel(s.status)}</Badge></div></div><InstallmentEditForm schedule={s} contractId={c.id}/></div>)}{d.schedules.length===0?<p className="py-8 text-center text-sm text-muted-foreground">Generate the schedule before recording a payment.</p>:null}</CardContent></Card>
 <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Card><CardHeader><CardTitle>Payment history</CardTitle></CardHeader><CardContent className="space-y-3">{d.payments.map(p=>{const receipt=receipts.get(p.id);return <div key={p.id} className="rounded-lg border p-3"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-medium">{p.payment_number}</p><p className="text-xs text-muted-foreground">{financeDate(p.payment_date)} · {financeStatusLabel(p.payment_method)}{receipt?` · ${receipt.receipt_number}`:''}</p></div><div className="text-right"><p className="font-semibold">{formatEtb(p.amount_etb)}</p><Badge>{financeStatusLabel(p.status)}</Badge></div></div><div className="mt-3 flex gap-2">{p.status==='submitted'?<form action={paymentAction.bind(null,p.id)}><input type="hidden" name="action" value="verify"/><Button type="submit" size="sm">Verify & issue receipt</Button></form>:null}{p.status==='verified'?<form action={paymentAction.bind(null,p.id)}><input type="hidden" name="action" value="reconcile"/><Button type="submit" size="sm">Reconcile</Button></form>:null}</div></div>})}{d.payments.length===0?<p className="text-sm text-muted-foreground">No payments recorded.</p>:null}</CardContent></Card>
 <Card><CardHeader><CardTitle>Sales commission</CardTitle><CardDescription>Calculated from the configured project rule.</CardDescription></CardHeader><CardContent className="space-y-3">{d.commissions.map(x=><div key={x.id} className="rounded-lg border p-3"><p className="font-semibold">{formatEtb(x.net_amount_etb)} net</p><p className="text-xs text-muted-foreground">Gross {formatEtb(x.gross_amount_etb)} · Withholding {formatEtb(x.withholding_amount_etb)}</p><Badge className="mt-2">{financeStatusLabel(x.status)}</Badge></div>)}{d.commissions.length===0?<form action={calculateCommissionAction.bind(null,c.id)} className="space-y-3"><label className="block space-y-1 text-sm font-medium">Sales agent<select name="agent_user_id" className="h-10 w-full rounded-lg border bg-background px-3">{d.profiles.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></label><Button type="submit">Calculate commission</Button></form>:null}</CardContent></Card></div>
 </div>}
